FROM wwliao/hpp_base:1.0.0--f6afa9eaa53cc9f176b9ed0d6a33767c8f8cbc21
LABEL maintainer="wen-wei.liao@yale.edu"

USER root

# GraphAligner v1.0.14
WORKDIR /opt/graphaligner
RUN conda install graphaligner=1.0.14

WORKDIR /data
